project_id = "vtlreobljodwflcjigft"

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.refresh-entitlement]
verify_jwt = false
